// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_BASEFLATBUFFER_BASE_SAMPLE_H_
#define FLATBUFFERS_GENERATED_BASEFLATBUFFER_BASE_SAMPLE_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 9 &&
              FLATBUFFERS_VERSION_REVISION == 23,
             "Non-compatible flatbuffers version included");

namespace Base {
namespace Sample {

struct Vec3;

struct Info;
struct InfoBuilder;

struct Message;
struct MessageBuilder;

struct Header;
struct HeaderBuilder;

struct Packet;
struct PacketBuilder;

enum PacketId : int8_t {
  PacketId_NONE = 0,
  PacketId_INFO = 1,
  PacketId_MESSAGE = 2,
  PacketId_MIN = PacketId_NONE,
  PacketId_MAX = PacketId_MESSAGE
};

inline const PacketId (&EnumValuesPacketId())[3] {
  static const PacketId values[] = {
    PacketId_NONE,
    PacketId_INFO,
    PacketId_MESSAGE
  };
  return values;
}

inline const char * const *EnumNamesPacketId() {
  static const char * const names[4] = {
    "NONE",
    "INFO",
    "MESSAGE",
    nullptr
  };
  return names;
}

inline const char *EnumNamePacketId(PacketId e) {
  if (::flatbuffers::IsOutRange(e, PacketId_NONE, PacketId_MESSAGE)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesPacketId()[index];
}

enum AnyPacket : uint8_t {
  AnyPacket_NONE = 0,
  AnyPacket_Info = 1,
  AnyPacket_Message = 2,
  AnyPacket_MIN = AnyPacket_NONE,
  AnyPacket_MAX = AnyPacket_Message
};

inline const AnyPacket (&EnumValuesAnyPacket())[3] {
  static const AnyPacket values[] = {
    AnyPacket_NONE,
    AnyPacket_Info,
    AnyPacket_Message
  };
  return values;
}

inline const char * const *EnumNamesAnyPacket() {
  static const char * const names[4] = {
    "NONE",
    "Info",
    "Message",
    nullptr
  };
  return names;
}

inline const char *EnumNameAnyPacket(AnyPacket e) {
  if (::flatbuffers::IsOutRange(e, AnyPacket_NONE, AnyPacket_Message)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesAnyPacket()[index];
}

template<typename T> struct AnyPacketTraits {
  static const AnyPacket enum_value = AnyPacket_NONE;
};

template<> struct AnyPacketTraits<Base::Sample::Info> {
  static const AnyPacket enum_value = AnyPacket_Info;
};

template<> struct AnyPacketTraits<Base::Sample::Message> {
  static const AnyPacket enum_value = AnyPacket_Message;
};

bool VerifyAnyPacket(::flatbuffers::Verifier &verifier, const void *obj, AnyPacket type);
bool VerifyAnyPacketVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Vec3 FLATBUFFERS_FINAL_CLASS {
 private:
  float x_;
  float y_;
  float z_;

 public:
  Vec3()
      : x_(0),
        y_(0),
        z_(0) {
  }
  Vec3(float _x, float _y, float _z)
      : x_(::flatbuffers::EndianScalar(_x)),
        y_(::flatbuffers::EndianScalar(_y)),
        z_(::flatbuffers::EndianScalar(_z)) {
  }
  float x() const {
    return ::flatbuffers::EndianScalar(x_);
  }
  float y() const {
    return ::flatbuffers::EndianScalar(y_);
  }
  float z() const {
    return ::flatbuffers::EndianScalar(z_);
  }
};
FLATBUFFERS_STRUCT_END(Vec3, 12);

struct Info FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef InfoBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NAME = 4,
    VT_POS = 6,
    VT_ROT = 8
  };
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  const ::flatbuffers::Vector<const Base::Sample::Vec3 *> *pos() const {
    return GetPointer<const ::flatbuffers::Vector<const Base::Sample::Vec3 *> *>(VT_POS);
  }
  const Base::Sample::Vec3 *rot() const {
    return GetStruct<const Base::Sample::Vec3 *>(VT_ROT);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyOffset(verifier, VT_POS) &&
           verifier.VerifyVector(pos()) &&
           VerifyField<Base::Sample::Vec3>(verifier, VT_ROT, 4) &&
           verifier.EndTable();
  }
};

struct InfoBuilder {
  typedef Info Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(Info::VT_NAME, name);
  }
  void add_pos(::flatbuffers::Offset<::flatbuffers::Vector<const Base::Sample::Vec3 *>> pos) {
    fbb_.AddOffset(Info::VT_POS, pos);
  }
  void add_rot(const Base::Sample::Vec3 *rot) {
    fbb_.AddStruct(Info::VT_ROT, rot);
  }
  explicit InfoBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Info> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Info>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Info> CreateInfo(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<const Base::Sample::Vec3 *>> pos = 0,
    const Base::Sample::Vec3 *rot = nullptr) {
  InfoBuilder builder_(_fbb);
  builder_.add_rot(rot);
  builder_.add_pos(pos);
  builder_.add_name(name);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Info> CreateInfoDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *name = nullptr,
    const std::vector<Base::Sample::Vec3> *pos = nullptr,
    const Base::Sample::Vec3 *rot = nullptr) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  auto pos__ = pos ? _fbb.CreateVectorOfStructs<Base::Sample::Vec3>(*pos) : 0;
  return Base::Sample::CreateInfo(
      _fbb,
      name__,
      pos__,
      rot);
}

struct Message FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef MessageBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TYPE = 4,
    VT_STR = 6
  };
  int32_t type() const {
    return GetField<int32_t>(VT_TYPE, 0);
  }
  const ::flatbuffers::String *str() const {
    return GetPointer<const ::flatbuffers::String *>(VT_STR);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_TYPE, 4) &&
           VerifyOffset(verifier, VT_STR) &&
           verifier.VerifyString(str()) &&
           verifier.EndTable();
  }
};

struct MessageBuilder {
  typedef Message Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_type(int32_t type) {
    fbb_.AddElement<int32_t>(Message::VT_TYPE, type, 0);
  }
  void add_str(::flatbuffers::Offset<::flatbuffers::String> str) {
    fbb_.AddOffset(Message::VT_STR, str);
  }
  explicit MessageBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Message> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Message>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Message> CreateMessage(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t type = 0,
    ::flatbuffers::Offset<::flatbuffers::String> str = 0) {
  MessageBuilder builder_(_fbb);
  builder_.add_str(str);
  builder_.add_type(type);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Message> CreateMessageDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t type = 0,
    const char *str = nullptr) {
  auto str__ = str ? _fbb.CreateString(str) : 0;
  return Base::Sample::CreateMessage(
      _fbb,
      type,
      str__);
}

struct Header FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef HeaderBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SIZE = 4,
    VT_CODE = 6
  };
  int16_t size() const {
    return GetField<int16_t>(VT_SIZE, 0);
  }
  int16_t code() const {
    return GetField<int16_t>(VT_CODE, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int16_t>(verifier, VT_SIZE, 2) &&
           VerifyField<int16_t>(verifier, VT_CODE, 2) &&
           verifier.EndTable();
  }
};

struct HeaderBuilder {
  typedef Header Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_size(int16_t size) {
    fbb_.AddElement<int16_t>(Header::VT_SIZE, size, 0);
  }
  void add_code(int16_t code) {
    fbb_.AddElement<int16_t>(Header::VT_CODE, code, 0);
  }
  explicit HeaderBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Header> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Header>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Header> CreateHeader(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int16_t size = 0,
    int16_t code = 0) {
  HeaderBuilder builder_(_fbb);
  builder_.add_code(code);
  builder_.add_size(size);
  return builder_.Finish();
}

struct Packet FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef PacketBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_HEADER = 4,
    VT_CONTENT_TYPE = 6,
    VT_CONTENT = 8
  };
  const Base::Sample::Header *header() const {
    return GetPointer<const Base::Sample::Header *>(VT_HEADER);
  }
  Base::Sample::AnyPacket content_type() const {
    return static_cast<Base::Sample::AnyPacket>(GetField<uint8_t>(VT_CONTENT_TYPE, 0));
  }
  const void *content() const {
    return GetPointer<const void *>(VT_CONTENT);
  }
  template<typename T> const T *content_as() const;
  const Base::Sample::Info *content_as_Info() const {
    return content_type() == Base::Sample::AnyPacket_Info ? static_cast<const Base::Sample::Info *>(content()) : nullptr;
  }
  const Base::Sample::Message *content_as_Message() const {
    return content_type() == Base::Sample::AnyPacket_Message ? static_cast<const Base::Sample::Message *>(content()) : nullptr;
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_HEADER) &&
           verifier.VerifyTable(header()) &&
           VerifyField<uint8_t>(verifier, VT_CONTENT_TYPE, 1) &&
           VerifyOffset(verifier, VT_CONTENT) &&
           VerifyAnyPacket(verifier, content(), content_type()) &&
           verifier.EndTable();
  }
};

template<> inline const Base::Sample::Info *Packet::content_as<Base::Sample::Info>() const {
  return content_as_Info();
}

template<> inline const Base::Sample::Message *Packet::content_as<Base::Sample::Message>() const {
  return content_as_Message();
}

struct PacketBuilder {
  typedef Packet Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_header(::flatbuffers::Offset<Base::Sample::Header> header) {
    fbb_.AddOffset(Packet::VT_HEADER, header);
  }
  void add_content_type(Base::Sample::AnyPacket content_type) {
    fbb_.AddElement<uint8_t>(Packet::VT_CONTENT_TYPE, static_cast<uint8_t>(content_type), 0);
  }
  void add_content(::flatbuffers::Offset<void> content) {
    fbb_.AddOffset(Packet::VT_CONTENT, content);
  }
  explicit PacketBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Packet> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Packet>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Packet> CreatePacket(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<Base::Sample::Header> header = 0,
    Base::Sample::AnyPacket content_type = Base::Sample::AnyPacket_NONE,
    ::flatbuffers::Offset<void> content = 0) {
  PacketBuilder builder_(_fbb);
  builder_.add_content(content);
  builder_.add_header(header);
  builder_.add_content_type(content_type);
  return builder_.Finish();
}

inline bool VerifyAnyPacket(::flatbuffers::Verifier &verifier, const void *obj, AnyPacket type) {
  switch (type) {
    case AnyPacket_NONE: {
      return true;
    }
    case AnyPacket_Info: {
      auto ptr = reinterpret_cast<const Base::Sample::Info *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case AnyPacket_Message: {
      auto ptr = reinterpret_cast<const Base::Sample::Message *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return true;
  }
}

inline bool VerifyAnyPacketVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types) {
  if (!values || !types) return !values && !types;
  if (values->size() != types->size()) return false;
  for (::flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifyAnyPacket(
        verifier,  values->Get(i), types->GetEnum<AnyPacket>(i))) {
      return false;
    }
  }
  return true;
}

inline const Base::Sample::Packet *GetPacket(const void *buf) {
  return ::flatbuffers::GetRoot<Base::Sample::Packet>(buf);
}

inline const Base::Sample::Packet *GetSizePrefixedPacket(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<Base::Sample::Packet>(buf);
}

inline bool VerifyPacketBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<Base::Sample::Packet>(nullptr);
}

inline bool VerifySizePrefixedPacketBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<Base::Sample::Packet>(nullptr);
}

inline void FinishPacketBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<Base::Sample::Packet> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedPacketBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<Base::Sample::Packet> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace Sample
}  // namespace Base

#endif  // FLATBUFFERS_GENERATED_BASEFLATBUFFER_BASE_SAMPLE_H_
