// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_DUBUECHOPACKET_DUBU_ECHO_H_
#define FLATBUFFERS_GENERATED_DUBUECHOPACKET_DUBU_ECHO_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 1 &&
              FLATBUFFERS_VERSION_REVISION == 21,
             "Non-compatible flatbuffers version included");

namespace DUBU {
namespace Echo {

struct Chatting;
struct ChattingBuilder;

struct Register;
struct RegisterBuilder;

struct Packet;
struct PacketBuilder;

enum PacketBody : uint8_t {
  PacketBody_NONE = 0,
  PacketBody_Chatting = 1,
  PacketBody_Register = 2,
  PacketBody_MIN = PacketBody_NONE,
  PacketBody_MAX = PacketBody_Register
};

inline const PacketBody (&EnumValuesPacketBody())[3] {
  static const PacketBody values[] = {
    PacketBody_NONE,
    PacketBody_Chatting,
    PacketBody_Register
  };
  return values;
}

inline const char * const *EnumNamesPacketBody() {
  static const char * const names[4] = {
    "NONE",
    "Chatting",
    "Register",
    nullptr
  };
  return names;
}

inline const char *EnumNamePacketBody(PacketBody e) {
  if (::flatbuffers::IsOutRange(e, PacketBody_NONE, PacketBody_Register)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesPacketBody()[index];
}

template<typename T> struct PacketBodyTraits {
  static const PacketBody enum_value = PacketBody_NONE;
};

template<> struct PacketBodyTraits<DUBU::Echo::Chatting> {
  static const PacketBody enum_value = PacketBody_Chatting;
};

template<> struct PacketBodyTraits<DUBU::Echo::Register> {
  static const PacketBody enum_value = PacketBody_Register;
};

bool VerifyPacketBody(::flatbuffers::Verifier &verifier, const void *obj, PacketBody type);
bool VerifyPacketBodyVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types);

struct Chatting FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ChattingBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4,
    VT_MESSAGE = 6
  };
  uint32_t id() const {
    return GetField<uint32_t>(VT_ID, 0);
  }
  const ::flatbuffers::String *message() const {
    return GetPointer<const ::flatbuffers::String *>(VT_MESSAGE);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_ID, 4) &&
           VerifyOffset(verifier, VT_MESSAGE) &&
           verifier.VerifyString(message()) &&
           verifier.EndTable();
  }
};

struct ChattingBuilder {
  typedef Chatting Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_id(uint32_t id) {
    fbb_.AddElement<uint32_t>(Chatting::VT_ID, id, 0);
  }
  void add_message(::flatbuffers::Offset<::flatbuffers::String> message) {
    fbb_.AddOffset(Chatting::VT_MESSAGE, message);
  }
  explicit ChattingBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Chatting> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Chatting>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Chatting> CreateChatting(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t id = 0,
    ::flatbuffers::Offset<::flatbuffers::String> message = 0) {
  ChattingBuilder builder_(_fbb);
  builder_.add_message(message);
  builder_.add_id(id);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Chatting> CreateChattingDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t id = 0,
    const char *message = nullptr) {
  auto message__ = message ? _fbb.CreateString(message) : 0;
  return DUBU::Echo::CreateChatting(
      _fbb,
      id,
      message__);
}

struct Register FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef RegisterBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4
  };
  uint32_t id() const {
    return GetField<uint32_t>(VT_ID, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_ID, 4) &&
           verifier.EndTable();
  }
};

struct RegisterBuilder {
  typedef Register Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_id(uint32_t id) {
    fbb_.AddElement<uint32_t>(Register::VT_ID, id, 0);
  }
  explicit RegisterBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Register> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Register>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Register> CreateRegister(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t id = 0) {
  RegisterBuilder builder_(_fbb);
  builder_.add_id(id);
  return builder_.Finish();
}

struct Packet FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef PacketBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_BODY_TYPE = 4,
    VT_BODY = 6
  };
  DUBU::Echo::PacketBody body_type() const {
    return static_cast<DUBU::Echo::PacketBody>(GetField<uint8_t>(VT_BODY_TYPE, 0));
  }
  const void *body() const {
    return GetPointer<const void *>(VT_BODY);
  }
  template<typename T> const T *body_as() const;
  const DUBU::Echo::Chatting *body_as_Chatting() const {
    return body_type() == DUBU::Echo::PacketBody_Chatting ? static_cast<const DUBU::Echo::Chatting *>(body()) : nullptr;
  }
  const DUBU::Echo::Register *body_as_Register() const {
    return body_type() == DUBU::Echo::PacketBody_Register ? static_cast<const DUBU::Echo::Register *>(body()) : nullptr;
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_BODY_TYPE, 1) &&
           VerifyOffset(verifier, VT_BODY) &&
           VerifyPacketBody(verifier, body(), body_type()) &&
           verifier.EndTable();
  }
};

template<> inline const DUBU::Echo::Chatting *Packet::body_as<DUBU::Echo::Chatting>() const {
  return body_as_Chatting();
}

template<> inline const DUBU::Echo::Register *Packet::body_as<DUBU::Echo::Register>() const {
  return body_as_Register();
}

struct PacketBuilder {
  typedef Packet Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_body_type(DUBU::Echo::PacketBody body_type) {
    fbb_.AddElement<uint8_t>(Packet::VT_BODY_TYPE, static_cast<uint8_t>(body_type), 0);
  }
  void add_body(::flatbuffers::Offset<void> body) {
    fbb_.AddOffset(Packet::VT_BODY, body);
  }
  explicit PacketBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Packet> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Packet>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Packet> CreatePacket(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    DUBU::Echo::PacketBody body_type = DUBU::Echo::PacketBody_NONE,
    ::flatbuffers::Offset<void> body = 0) {
  PacketBuilder builder_(_fbb);
  builder_.add_body(body);
  builder_.add_body_type(body_type);
  return builder_.Finish();
}

inline bool VerifyPacketBody(::flatbuffers::Verifier &verifier, const void *obj, PacketBody type) {
  switch (type) {
    case PacketBody_NONE: {
      return true;
    }
    case PacketBody_Chatting: {
      auto ptr = reinterpret_cast<const DUBU::Echo::Chatting *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case PacketBody_Register: {
      auto ptr = reinterpret_cast<const DUBU::Echo::Register *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return true;
  }
}

inline bool VerifyPacketBodyVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types) {
  if (!values || !types) return !values && !types;
  if (values->size() != types->size()) return false;
  for (::flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifyPacketBody(
        verifier,  values->Get(i), types->GetEnum<PacketBody>(i))) {
      return false;
    }
  }
  return true;
}

inline const DUBU::Echo::Packet *GetPacket(const void *buf) {
  return ::flatbuffers::GetRoot<DUBU::Echo::Packet>(buf);
}

inline const DUBU::Echo::Packet *GetSizePrefixedPacket(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<DUBU::Echo::Packet>(buf);
}

inline bool VerifyPacketBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<DUBU::Echo::Packet>(nullptr);
}

inline bool VerifySizePrefixedPacketBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<DUBU::Echo::Packet>(nullptr);
}

inline void FinishPacketBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<DUBU::Echo::Packet> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedPacketBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<DUBU::Echo::Packet> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace Echo
}  // namespace DUBU

#endif  // FLATBUFFERS_GENERATED_DUBUECHOPACKET_DUBU_ECHO_H_
